-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 23:36:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `s_no` INT NOT NULL,
  `s_name` VARCHAR(45) NULL,
  `s_pwd` VARCHAR(45) NULL,
  PRIMARY KEY (`s_no`),
  UNIQUE INDEX `s_id_UNIQUE` (`s_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `p_no` INT NOT NULL,
  `p_name` VARCHAR(45) NULL,
  `p_psw` VARCHAR(45) NULL,
  PRIMARY KEY (`p_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attend` (
  `s_no` INT NOT NULL,
  `sub_code` VARCHAR(5) NULL,
  `p_no` INT NOT NULL,
  `att_grade` INT(3) NULL DEFAULT 0,
  PRIMARY KEY (`s_no`, `p_no`),
  INDEX `fk_attend_p_no_idx` (`p_no` ASC) VISIBLE,
  CONSTRAINT `fk_attend_s_no`
    FOREIGN KEY (`s_no`)
    REFERENCES `mydb`.`student` (`s_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attend_p_no`
    FOREIGN KEY (`p_no`)
    REFERENCES `mydb`.`professor` (`p_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`score` (
  `s_no` INT NOT NULL,
  PRIMARY KEY (`s_no`),
  CONSTRAINT `fk_score_s_no`
    FOREIGN KEY (`s_no`)
    REFERENCES `mydb`.`student` (`s_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`board` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `crator_id` INT NOT NULL,
  `b_title` VARCHAR(150) NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`b_id`),
  INDEX `fd_board_crator_id_idx` (`crator_id` ASC) VISIBLE,
  CONSTRAINT `fd_board_crator_id`
    FOREIGN KEY (`crator_id`)
    REFERENCES `mydb`.`professor` (`p_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
